http://git.eclipse.org/gitroot/e4/eclipse.platform.runtime.e4.git           
http://git.eclipse.org/gitroot/e4/eclipse.platform.ui.compat.git          
http://git.eclipse.org/gitroot/e4/eclipse.platform.ui.e4.git           
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.databinding.git		 
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.deeplink.git           
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.installer.git          
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.languages.git		 
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.releng.git	 
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.resources.git		 
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.search.git         
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.tools.git		 
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.ui.git		 
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.utils.git         
http://git.eclipse.org/gitroot/e4/org.eclipse.e4.xwt.git	 
http://git.eclipse.org/gitroot/e4/org.eclipse.jdt.core.git	 
http://git.eclipse.org/gitroot/e4/org.eclipse.migration.git
http://git.eclipse.org/gitroot/equinox/rt.equinox.binaries.git	   
http://git.eclipse.org/gitroot/equinox/rt.equinox.bundles.git	
http://git.eclipse.org/gitroot/equinox/rt.equinox.framework.git
http://git.eclipse.org/gitroot/equinox/rt.equinox.incubator.git
http://git.eclipse.org/gitroot/equinox/rt.equinox.p2.cudf.git	
http://git.eclipse.org/gitroot/equinox/rt.equinox.p2.git	